apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-hen
spec:
  containers:
  - image: redis:alpine
    name: redis-storage-hen
    volumeMounts:
    - mountPath: /data/redis
      name: data-redis-volume
  volumes:
  - name: data-redis-volume
    emptyDir: {}
